services:
  bookmanament.api:
    image: bookmanament.api
    build:
      context: .
      dockerfile: BookManament.API/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookmanagement_sqlserver
    environment:
      SA_PASSWORD: "NewSimplePassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./data-mssql:/var/opt/mssql/data
    networks:
      - bookmanagement_network

volumes:
  sqlserver_data:

networks:
  bookmanagement_network: